In [1]:
import numpy as np
import pandas as pd

In [2]:
df2=pd.read_csv("covid2.csv")

In [3]:
df2.head()

,Unnamed: 0,iso_code,continent,location,date,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,0,AFG,Asia,Afghanistan,2020-02-24,3.892834e+07,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.50,64.83,0.511
1,1,OWID_AFR,NaN,Africa,2020-02-13,1.340598e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,ALB,Europe,Albania,2020-02-25,2.877800e+06,104.871,38.0,13.188,8.643,11803.431,1.1,304.195,10.08,7.1,51.2,NaN,2.89,78.57,0.795
3,3,DZA,Africa,Algeria,2020-02-25,4.385104e+07,17.348,29.1,6.211,3.857,13913.839,0.5,278.364,6.73,0.7,30.4,83.741,1.90,76.88,0.748
4,4,AND,Europe,Andorra,2020-03-02,7.726500e+04,163.755,NaN,NaN,NaN,NaN,NaN,109.135,7.97,29.0,37.8,NaN,NaN,83.73,0.868

In [4]:
for index in df2.index/100:
    print(df2.loc[index]['iso_code'])

NameError: name 'iso_code' is not defined