In [1]:
import numpy as np
import pandas as pd

In [2]:
df2=pd.read_csv("covid2.csv")

In [7]:
df2.head()
df2.index

RangeIndex(start=0, stop=436, step=1)

In [18]:
for ind in df2.index:
    if (len(df2.loc[ind]['iso_code'])!=3):
        print(df2.loc[ind]['iso_code'])
        df2=df2.drop(index=ind)

OWID_AFR
OWID_ASI
OWID_EUR
OWID_EUN
OWID_INT
OWID_KOS
OWID_NAM
OWID_CYN
OWID_OCE
OWID_SAM
OWID_WRL
OWID_AFR
OWID_ASI
OWID_EUR
OWID_EUN
OWID_INT
OWID_KOS
OWID_NAM
OWID_CYN
OWID_OCE
OWID_SAM
OWID_WRL

In [19]:
df2.index

Int64Index([  0,   2,   3,   4,   5,   6,   7,   8,   9,  11,
            ...
            425, 426, 427, 428, 429, 430, 431, 433, 434, 435],
           dtype='int64', length=414)

In [23]:
df2.describe()

,Unnamed: 0,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,414.000000,4.140000e+02,394.000000,370.000000,366.000000,368.000000,374.000000,246.000000,374.000000,386.000000,288.000000,284.000000,188.000000,336.000000,410.000000,372.000000
mean,217.594203,3.747101e+07,459.825350,30.268649,8.629120,5.452174,19199.099540,14.073171,262.562877,8.083938,10.667361,32.786620,50.165947,3.010583,73.266634,0.722403
std,125.959694,1.433073e+08,2137.371372,9.170460,6.169397,4.201053,20631.624856,20.314977,120.911992,4.388769,10.696848,13.538237,31.958377,2.439936,7.622090,0.150451
min,0.000000,8.090000e+02,0.137000,15.100000,1.144000,0.526000,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.280000,0.394000
25%,109.250000,1.031042e+06,36.253000,22.000000,3.447250,2.040750,3924.303000,0.625000,170.358750,5.310000,1.900000,21.600000,19.351000,1.300000,67.920000,0.601000
50%,217.500000,7.132530e+06,85.129000,29.400000,6.211000,3.698500,12236.706000,2.500000,243.964000,7.140000,6.250000,32.250000,48.753000,2.398500,74.530000,0.741000
75%,326.750000,2.650397e+07,212.865000,38.700000,14.115500,8.651750,27114.374750,22.225000,332.934500,10.390000,19.150000,41.300000,82.502000,3.895750,78.880000,0.838000
max,435.000000,1.439324e+09,20546.766000,48.200000,27.049000,18.493000,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,98.999000,13.800000,86.750000,0.957000

In [22]:
df2.to_csv('covid2.csv')